#!/usr/bin/env node
/*
 * gen-sources.js - emits sources.cmake.
 *
 * Adapted from node-onlykey-emulator/emulator/scripts/gen-sources.js. That one
 * emits sources.gypi because gyp cannot glob; CMake *can* glob, but globbing
 * hides new files from the configure step until a manual re-run, and the
 * exclusion rules below are not expressible as globs anyway. So the list stays
 * generated, and stays reviewable.
 *
 * EXCLUDE holds files that must not be compiled as their own translation unit:
 * bare-metal drivers we replace, and the mlkem/mldsa `src/` trees, which the
 * monolithic mlkem_native.c / mldsa_native.c #include wholesale (compiling
 * them separately would duplicate every symbol - see libraries/onlykey/BUILD.md).
 */
'use strict';

const fs = require('fs');
const path = require('path');

const OKEMU = path.resolve(__dirname, '..');
/* okemu -> android -> ok-rn -> the checkouts root holding every component. */
const CHECKOUTS = path.resolve(OKEMU, '..', '..', '..');
const STAGE = path.join(OKEMU, '.stage');
const LIB = path.join(STAGE, 'libraries');
const STAGE_CORE = path.join(STAGE, 'core');
const ARDUINO = path.join(CHECKOUTS, 'arduino-1.6.5-r5-teensy_127', 'arduino-1.6.5-r5');
const TLIB = path.join(ARDUINO, 'hardware', 'teensy', 'avr', 'libraries');

const SRC_RE = /\.(c|cpp)$/;

const LIB_DIRS = [
  'onlykey', 'Crypto', 'SoftTimer', 'T3Mac', 'base64', 'password',
  'sha1', 'sha256', 'totp', 'tweetnacl', 'justhashtweetnacl', 'uECC',
  'ykcore', 'yksim', 'randombytes', 'fido2', 'tinycbor', 'mbedtls-2.4.0',
];

const EXCLUDE = new Set([
  /* replaced by okemu/src or core-override */
  'flashkinetis.cpp',          // -> src/okemu_flash.cpp
  'Adafruit_NeoPixel.cpp',     // -> shim/Adafruit_NeoPixel.h
  'esp8266.c',
  /* the Teensy core's own entry point; the JNI layer drives setup()/loop() */
  'main.cpp',
  /* the emulator's N-API layer; we have jni/okemu_jni.cpp instead */
  'addon.cpp',
]);

/* Path fragments that disqualify a file wherever it appears. */
const EXCLUDE_PATH = [
  `${path.sep}examples${path.sep}`,
  `${path.sep}test${path.sep}`,
  `${path.sep}tests${path.sep}`,
  /* #included by the monolithic mlkem_native.c / mldsa_native.c */
  `${path.sep}utility${path.sep}src${path.sep}`,
  `${path.sep}utility${path.sep}mldsa_src${path.sep}`,
];

function walk(dir, recurse, out) {
  if (!fs.existsSync(dir)) return out;
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      if (recurse) walk(p, recurse, out);
      continue;
    }
    if (!SRC_RE.test(ent.name)) continue;
    if (EXCLUDE.has(ent.name)) continue;
    if (EXCLUDE_PATH.some((frag) => p.includes(frag))) continue;
    out.push(p);
  }
  return out;
}

const sources = [];

/* 1. our own HAL sources (jni/ is added by CMakeLists directly, at C++17) */
walk(path.join(OKEMU, 'src'), false, sources);

/* 2. staged Teensy core (OnlyKey's USB stack + our overrides overlaid, the
 *    bare-metal files removed) */
walk(STAGE_CORE, false, sources);

/* 3. OnlyKey's vendored libraries */
for (const d of LIB_DIRS) walk(path.join(LIB, d), false, sources);
/* the PQC monoliths live one level down */
walk(path.join(LIB, 'onlykey', 'utility'), false, sources);

/* 4. Arduino Time library (firmware calls now()); staged, not referenced in
 *    place - see defuseTimeHeader() in stage.js. */
walk(path.join(LIB, 'Time'), false, sources);

/* CMake wants forward slashes even on Windows. */
const rel = sources
  .map((p) => path.relative(OKEMU, p).split(path.sep).join('/'))
  .sort();

const out =
  '# Generated by scripts/gen-sources.js - do not edit.\n' +
  `# ${rel.length} translation units.\n` +
  'set(OKEMU_SOURCES\n' +
  rel.map((r) => `  \${OKEMU_DIR}/${r}`).join('\n') +
  '\n)\n';

const outPath = path.join(OKEMU, 'sources.cmake');
fs.writeFileSync(outPath, out);
console.log(`gen-sources: ${rel.length} translation units -> sources.cmake`);
