/*
 * GENERATED by tools/backup-fixture.js - a backup a v3.0.4 key TYPED.
 *
 * A module rather than a .txt because this is read on the phone, where
 * there is no filesystem - Metro bundles what is required.
 *
 * An EMULATED key's slots, under a passphrase this repo already holds
 * (__e2e_tests__/helpers/backupPassphrase.js). A fixture, not a secret,
 * and never to be produced from a real key.
 */
'use strict';

module.exports = "-----BEGIN ONLYKEY BACKUP-----\nymnKNbR99vl/Y7P6vq0CobKgHxRUlQ+wPZ0J03QBwRH+ayVAT7X8atSxmoRQUbQrJWp5zI48xL4g\n1C6Uk5/iiu5dmPpOnnr65KDPK/v+GaznOX2jez9L52b6Mo4MhXEq6JEp8h+nWeOv0/xEgdxt78Y6\nUJ6B8/mtlqZbW0urKuVcGjlAZNdFVH2k8DMqY0Ny/Q8wiIHZjJ0ZV8AOHHSep46NemdKGAGIMaKg\nkQ0MXVA0lfDv80xoqPju7ZYJSYwEaTDwNBdhEEjg0gMkY83GnWN7hWiOdaSgosSniRcUW4nHpRlO\nmrbCFdT/3gaBItjkOlGUxeYsfrL4SKSK8hZ7MI7hMeEb9vyyLObltSXtnaIzvAHiCo1SGcKvETdG\nSZ4TVptYP/PcV8jjFOJc+OPANgFeDy0QHihms6tmzEQKCfKlAp3TbK52ph8eqIA6Nx09rpV5e8PA\nGQ4y8eQUOKKo1l05jnHIGWazzdfwWJb7PLvw0THn7dgyvdhKP2ceKUUchjTW7vZvmv2LmLRjqkEm\nUso2yoEzemz84ThczuoU7lgCqIAUnsPmz4dFqpHJYyVpUCbOannurrYa6Nboij3hSnXqQfZfmN7K\nvVaTixI7soEZ3ncbOpD91RYdakE1EnVNqNaMZ00nSnNnIcC84eOZtbV/wcTcxo6bxCcoP/PNtA0L\nfjCii7+CLYH4t0IX+VRBO82eWxwobDO7ItHlki+RutxR8T6PJzC7d7kdsOcWyDeCuWU=\n--h3Iod9v1WcrmQimKD9PQIxnS43yNS+pxvaxqpZZGzM8=\n-----END ONLYKEY BACKUP-----";
