// Auto-generated by test-moniker CLI. Do not edit.
module.exports = [
    require('./1-softKey.e2e.js'),
    require('./2-buttonProbe.e2e.js'),
    require('./3-deviceFlow.e2e.js'),
    require('./4-ctapFlow.e2e.js')
];
