// Auto-generated by test-moniker CLI. Do not edit.
module.exports = [
    require('./0-provision.e2e.js'),
    require('./1-softKey.e2e.js'),
    require('./2-buttonProbe.e2e.js'),
    require('./3-deviceFlow.e2e.js'),
    require('./4-ctapFlow.e2e.js'),
    require('./5-presence.e2e.js'),
    require('./6-bridge.e2e.js'),
    require('./7-pressBands.e2e.js'),
    require('./8-keystrokes.e2e.js'),
    require('./9-cryptoSign.e2e.js'),
    require('./10-derive.e2e.js'),
    require('./11-compositePgp.e2e.js'),
    require('./12-identity.e2e.js'),
    require('./13-deriveParity.e2e.js'),
    require('./14-biometrics.e2e.js')
];
